### ISSUE TITLE
UnboundLocalError: local variable 'sents_len' referenced before assignment

### ISSUE THREAD

**Issue by ssaleri** [zhaochaocs/DualEnc#5]
Hi everyone,
I was trying to reproduce the steps, I've put the three folders in ../data/webnlg/ but when I do:

`sh planning.sh`

The outputs says:

> Traceback (most recent call last):
>   File "../../webnlg_eval_scripts/webnlg_gcnonmt_input.py", line 531, in <module>
>     main(sys.argv[1:])
>   File "../../webnlg_eval_scripts/webnlg_gcnonmt_input.py", line 527, in main
>     input_files(inputdir, parts=['train', 'dev'], negraph=ngraph, lowercased=lowercased)
>   File "../../webnlg_eval_scripts/webnlg_gcnonmt_input.py", line 466, in input_files
>     b.fill_benchmark(files)
>   File "/Users/simone/DualEnc/webnlg_eval_scripts/benchmark_reader.py", line 184, in fill_benchmark
>     entry.create_lex(child, int(size))
>   File "/Users/simone/DualEnc/webnlg_eval_scripts/benchmark_reader.py", line 146, in create_lex
>     lex = Lexicalisation(lex_text, comment, lid, tripleset, refs, lex_template, sents_len)
> UnboundLocalError: local variable 'sents_len' referenced before assignment

Any idea to make it work? Thank you

**Comment by ssaleri** [comment]
**Solution**:
I was using an updated version of the WebNLG dataset, you must use the v1.5 provided in the links
